- name: Install prequisites
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Ubuntu - install unzip (acl needed by Ansible to become an unprivileged user)
      apt:
        name:
          - acl
          - unzip
        state: present
        update_cache: yes
      register: apt_res
      retries: 3
      until: apt_res is success
      when: ansible_distribution == 'Ubuntu'
    - name: RedHat - install unzip
      yum:
        name:
          - unzip
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'
    - name: Debian - install unzip
      apt:
        name:
          - unzip
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
- name: Get GEOG data
  hosts: all
  strategy: free
  tasks:
    - name: Download GEOG data
      get_url:
        url: "https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_high_res_mandatory.tar.gz"
        dest: "{{ansible_env['HOME']}}"
        mode: 0755
    - name: Extract archive
      # Using absolute path to avoid an ansible issue with gtar and relative paths
      unarchive:
        src: "{{ansible_env['HOME']}}/geog_high_res_mandatory.tar.gz"
        dest: "{{ansible_env['HOME']}}"
        remote_src: yes
    - name: Remove archive
      file:
        path: "{{ansible_env['HOME']}}/geog_high_res_mandatory.tar.gz"
        state: absent
    - name: Move foo to bar
      command: mv "{{ansible_env['HOME']}}/WPS_GEOG" "{{ansible_env['HOME']}}/{{ OUTPUT_DIRECTORY }}"